# Generated by Django 5.2.3 on 2025-07-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AadhaarData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('gender', models.CharField(blank=True, max_length=15, null=True)),
                ('aadhaar_number', models.CharField(max_length=15, unique=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
